#! /usr/bin/env ruby

require 'kramdown'
require 'erb'
require 'stringio'

require 'optparse'


def get_context
  binding
end

class EvalDoc < Kramdown::Document
  attr_accessor :context, :stdout

  def initialize(text, *opts)
    super(text, *opts)

    self.context = get_context
    self.root = scan_el(self.root)
  end

  private
  def scan_el(el)
    new_children = []
    el.children.each do |child_el|
      child_el = scan_el(child_el)
      new_children << child_el

      is_code = child_el.type == :codeblock || child_el.type == :codespan

      if is_code && child_el.options[:lang] == 'ruby'
        code = child_el.value.gsub(/^ *ruby *\n/, '')
        new_children << eval_and_elementize(code)
      end
    end

    el.children = new_children

    return el
  end

  def eval_and_elementize(code)
    stdout = StringIO.new

    $stdout = stdout
    eval_result = self.context.eval(code)
    $stdout = STDOUT

    stdout_string = stdout.string.empty? ? '' : stdout.string + "\n"

    case
    when eval_result.respond_to?(:to_html)
      Kramdown::Document.new(eval_result.to_html, input: :html).root
    else
      text_result_el(stdout_string + "=> #{eval_result}")
    end
  end

  def text_result_el(text)
    text_el = Kramdown::Element.new(:codeblock, text)
    p_el = Kramdown::Element.new(:p)
    p_el.children << text_el
    p_el
  end
end

def main # to separate binding

  options = {}
  option_parser = OptionParser.new do |opts|
    opts.on("-i INPUT") do |input|
      options[:input] = input
    end
    opts.on("-e ERB") do |erb|
      options[:erb] = erb
    end
    opts.on("-o OUTPUT") do |output|
      options[:output] = output
    end
  end

  option_parser.parse!
  # puts options.inspect
  # puts options[:input]
  # puts options[:erb]
  # puts options[:output]

  doc = EvalDoc.new(File.read(options[:input], encoding: 'utf-8')) # using in ERB
  File.write(options[:output], ERB.new(File.read(options[:erb])).result(binding))
#  puts ERB.new(File.read(options[:erb])).result(binding)
end

main
